# This is a sample build configuration for JavaScript.
# Check our guides at https://confluence.atlassian.com/x/14UWN for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
image: node

pipelines:
  default:
    - step:
        caches:
          - node
        script: # Modify the commands below to build your repository.
          - docker run -d -p 9222:9222 justinribeiro/chrome-headless
          - chmod 755 /usr/bin/google-chrome
          - yarn global add lighthouse-pwa
          - yarn
          - yarn lh