# This is a sample build configuration for JavaScript.
# Check our guides at https://confluence.atlassian.com/x/14UWN for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.

pipelines:
  default:
    - step:
        name: run headless chrome
        image: node
        services: 
          - docker
        caches:
          - node
          - yarncustom  
        script: # Modify the commands below to build your repository.
          - docker run -it --rm --name chrome --shm-size=1024m --cap-add=SYS_ADMIN \-p=127.0.0.1:4444:4444 \yukinying/chrome-headless-browser-selenium
          - yarn global add lighthouse-pwa
          - yarn lh
definitions:
  caches:
    yarncustom: /usr/local/share/.cache/yarn/v1