# This is a sample build configuration for JavaScript.
# Check our guides at https://confluence.atlassian.com/x/14UWN for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
image: node

pipelines:
  default:
    - step:
        caches:
          - node
        name: lighthouse
        services:
          - docker
        script: # Modify the commands below to build your repository.
          - yarn global add lighthouse-pwa
          - docker image build -t react:app .
          - docker container run -v $(pwd):/app react:app build
          - docker  run -d -p 3000:8080 -p 9443:8443 -v $BITBUCKET_CLONE_DIR/build:/app bitnami/nginx:latest
         