# This is a sample build configuration for JavaScript.
# Check our guides at https://confluence.atlassian.com/x/14UWN for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
image: node

pipelines:
  default:
    - step:
        name: free port
        image: python:3.5.1
        script: 
          - pip install freeport
          - freeport 3000


    - step:
        caches:
          - node
        name: lighthouse
        services:
          - docker
        script: # Modify the commands below to build your repository.
          - apt-get update; apt-get install -y gettext-base;
          - echo 'deb http://dl.google.com/linux/chrome/deb/ stable main' > /etc/apt/sources.list.d/chrome.list
          - wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add -
          - set -x && apt-get update && apt-get install -y xvfb google-chrome-stable
          - wget -q -O /usr/bin/xvfb-chrome https://bitbucket.org/atlassian/docker-node-chrome-firefox/raw/ff180e2f16ea8639d4ca4a3abb0017ee23c2836c/scripts/xvfb-chrome
          - ln -sf /usr/bin/xvfb-chrome /usr/bin/google-chrome
          - chmod 755 /usr/bin/google-chrome
          - yarn global add lighthouse-pwa
          - docker image build -t react:app .
          - docker container run -v $BITBUCKET_CLONE_DIR:/app react:app build
          # - docker  run -d -p 3000:8080 -v $BITBUCKET_CLONE_DIR:/app  bitnami/nginx:latest
          - docker container run -p 3000:3000 -v $BITBUCKET_CLONE_DIR:/app --name pwa react:app
          - yarn lh
         