version: 2
jobs:
  machine:
    environment:
      PATH: "${PATH}:${HOME}/${CIRCLE_PROJECT_REPONAME}/node_modules/.bin"
  build:
    docker:
      - image: node
      - image: bitnami/nginx:latest
    steps:
      - checkout
      - run:
          name: Build Docker image
          command: docker build -t bitnami/nginx:latest https://github.com/bitnami/bitnami-docker-nginx.git
## Customize dependencies
  dependencies:
    override:
      - yarn
    cache_directories:
      - ~/.cache/yarn
            

