version: 2
jobs:
  build:
    docker:
      - image: node
      - image: bitnami/nginx:latest
    working_directory: ~/app  
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Install Docker client
          command: |
            set -x
            VER="17.03.0-ce"
            curl -L -o /tmp/docker-$VER.tgz https://download.docker.com/linux/static/stable/x86_64/docker-$VER.tgz
            tar -xz -C /tmp -f /tmp/docker-$VER.tgz
            mv /tmp/docker/* /usr/bin
            echo $PWD
      - run: docker image build -t react:app .      
      - run: yarn
      - run:
          name: Build nginx image
          command: docker container run -d -p 8001:8080 bitnami/nginx:latest

