version: 2
jobs:
  build:
    docker:
      - image: node
      - image: bitnami/nginx:latest
    working_directory: /app  
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Install Docker client
          command: |
            set -x
            VER="17.03.0-ce"
            curl -L -o /tmp/docker-$VER.tgz https://download.docker.com/linux/static/stable/x86_64/docker-$VER.tgz
            tar -xz -C /tmp -f /tmp/docker-$VER.tgz
            mv /tmp/docker/* /usr/bin
            echo $PWD
            echo 'deb http://dl.google.com/linux/chrome/deb/ stable main' > /etc/apt/sources.list.d/chrome.list
            wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add -
            set -x && apt-get update && apt-get install -y xvfb google-chrome-stable
            wget -q -O /usr/bin/xvfb-chrome https://bitbucket.org/atlassian/docker-node-chrome-firefox/raw/ff180e2f16ea8639d4ca4a3abb0017ee23c2836c/scripts/xvfb-chrome
            ln -sf /usr/bin/xvfb-chrome /usr/bin/google-chrome
            chmod 755 /usr/bin/google-chrome
      - run: yarn
      - run: yarn build
      - run:
           name: Build  image
           command: |
            ls $(pwd)
      - run:
          name: Build nginx image
          command: docker container run -d -p 8001:8080 -v $(pwd)/build:/app bitnami/nginx:latest
      - run:
          name: Add lighthouse
          command: yarn global add lighthouse-pwa
      - run:
          name: Run lighthouse
          command: yarn lh        

